config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  get 'profile', to: 'pages#profile'
  get '/gears', to: 'gears#index'


  resources :gears, only: %i[index new create show] do
    resources :reservations, only: %i[new create]
  end
  resources :reservations, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/gear.rb
class Gear < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :destroy
  attribute :image_url, :string
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_one_attached :photo

  validates :price, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_name_and_description,
  against: [ :name, :description ],
  using: {
    tsearch: { prefix: true }
  }
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :gear

  validates :date_de_debut, presence: true
  validates :date_de_fin, presence: true

  def cout_location
    (date_de_fin - date_de_debut) * gear.price
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :reservation
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  attr_accessor :telephone

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :gears, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :reserved_gears, through: :reservations, source: "gears"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?



  private

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/gears_controller.rb
class GearsController < ApplicationController
  def index
    @gears = Gear.all
    @markers = @gears.geocoded.map do |gear|
      {
        lat: gear.latitude,
        lng: gear.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { gear: gear }),
        marker_html: render_to_string(partial: "marker", locals: { gear: gear })
      }
    end
    if params[:query].present?
      sql_query = <<~SQL
        gears.name ILIKE :query
        OR gears.description ILIKE :query
      SQL
      @gears = Gear.joins(:user).where(sql_query, query: "%#{params[:query]}%", localisation: "%#{params[:localisation]}%")
    elsif params[:localisation].present?
      @coordinates = Geocoder.coordinates(params[:localisation])
      @latitude = @coordinates[0]
      @longitude = @coordinates[1]
      @gears = Gear.near([@latitude, @longitude], 10)
    else
      @gears = Gear.all
    end
    # OR gears.localisation ILIKE :localisation
  end

  def new
    @gear = Gear.new
  end

  def create
    @gear = Gear.new(gear_params)

    if @gear.save
      redirect_to gears_path, notice: "L'équipement a été ajouté avec succès."
    else
      render :new
    end
  end

  def show
    @gear = Gear.find(params[:id])
    @reservation = Reservation.new
    @disable_dates = @gear.reservations.map do |reservation|
      {
        from: reservation.date_de_debut,
        to: reservation.date_de_fin
      }
    end
  end

  private

  def gear_params
    params.require(:gear).permit(:name, :description, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def profile
    @user = current_user
    @reservations = current_user.reservations
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]

  def index
    @reservations = Reservation.all
  end

  def new
    @reservation = Reservation.new
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to gears_path, notice: 'La réservation a été supprimée avec succès.'
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.user = current_user
    @reservation.gear = Gear.find(params[:gear_id])
    if @reservation.save
      redirect_to profile_path, notice: "La réservation a été créée avec succès."
    else
      render :new
    end
  end

  private

  def reservation_params
    params.require(:reservation).permit(:date_de_debut, :date_de_fin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/equipments/new.html.erb
<h1>Ajouter un nouvel équipement à louer</h1>

<%= form_for @equipment, url: equipments_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit 'Créer' %>
  </p>
<% end %>

app/views/gears/_form.html.erb
<%= simple_form_for(@gear) do |g| %>
  <%= g.error_notification %>
  <%= g.error_notification message: g.object.errors[:base].to_sentence if g.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= g.input :name %>
    <%= g.input :address,
      input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
      wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
    %>
  </div>

  <div class="form-actions">
    <%= g.button :submit %>
  </div>
<% end %>

app/views/gears/_info_window.html.erb
<div class="p-2">
  <h2><%= link_to gear.name, gear_path(gear) %></h2>
  <p class="mb-0"><%= gear.address %></p>
</div>

app/views/gears/_marker.html.erb
<%= image_tag("gears_image/red_marker.png", height: 30, width: 30, alt: "Image") %>

app/views/gears/index.html.erb
<div class="banner2">
  <div class="container">
    <h1>Liste des équipements sportifs</h1>
    <div class="cards">
      <% @gears.each do |gear| %>
        <div class="gear-card">
          <%= cl_image_tag gear.photo.key %>
          <h3><%= gear.name %></h3>
          <p><%= gear.description %></p>
          <%= link_to "Réserver", gear_path(gear), class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>


    <div class='container mt-5'>
    <div style="width: 100%; height: 600px;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  </div>
</div>

app/views/gears/new.html.erb
<div class="container">
  <h1>Ajouter un nouvel équipement à louer</h1>

  <%= simple_form_for @gear do |f| %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :price %>
      <%= f.input :address %>
      <%= f.input :image_url %>
      <%= f.submit 'Créer' %>
  <% end %>
</div>

app/views/gears/show.html.erb
<div class="container mt-navbar">
  <h1><%= @gear.name %></h1>
  <h4>loué par <%= @gear.user.first_name %></h4>
  <p><%= @gear.address %></p>
  <div class="cards">
    <div class="card-product text-black position-relative">
      <%= cl_image_tag @gear.photo.key %>
      <p class="ps-2"><%= @gear.description %></p>
      <p class="position-absolute quezac"><%= @gear.price %> €</p>
    </div>

  </div>
  <div class="container">
    <%= simple_form_for [@gear, @reservation], data: { controller: "datepicker", datepicker_disable_value: @disable_dates.to_json } do |f| %>
      <div class="d-flex">
        <%= f.input :date_de_debut,
            as: :string,
            input_html: { data: { datepicker_target: "start" } } %>
        <%= f.input :date_de_fin,
            as: :string,
            input_html: { data: { datepicker_target: "end" } } %>
      </div>
      <%= submit_tag "Réserver" %>
    <% end %>
  </div>
</div>


<%# <h2>Coordonnées du propriétaire</h2> %>
<%# <p>Téléphone : <%= @gear.proprietaire.telephone</p> %>
<%# <p>Email : <%= @gear.proprietaire.email %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GearSwap</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.css" type="text/css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <div class="main-container">
      <%= yield %>
    </div>
     <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="container">
    <%= form_with url: gears_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Trouver un équipement..."
      %>
      <%= text_field_tag :localisation,
      params[:localisation],
      class: "form-control",
      placeholder: "Saisir une localisation..."
      %>
      <div class="offset-button">
        <%= submit_tag "Search", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="banner3">
  <div class="container mt-navbar">
    <h1>Profil de l'utilisateur</h1>
    <p>Nom : <%= @user.last_name %></p>
    <p>Prénom : <%= @user.first_name %></p>
    <p>Email : <%= @user.email %></p>
  </div>
  <div class="container mt-5">
    <h1>Mes réservations</h1>
    <div class="cards">
      <% if @reservations.nil? %>
        <p>Vous n'avez aucune réservation pour le moment.</p>
      <% else %>
        <% @reservations.each do |reservation| %>
          <div class="card-product">
            <%= image_tag reservation.gear.photo %>
            <div class="card-product-infos text-black">
              <p><strong>Coût de la location:</strong> <%= reservation.cout_location %> €</p>
              <p><strong>Dates de location:</strong> <%= reservation.date_de_debut.strftime('%d/%m/%Y') %> - <%= reservation.date_de_fin.strftime('%d/%m/%Y') %></p>
              <%= button_to "Supprimer", reservation_path(reservation), method: :delete, data: { confirm: "Êtes-vous sûr de vouloir supprimer cette réservation ?" }, class: "btn btn-danger" %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/reservations/index.html.erb
<h1>Mes réservations</h1>

<% if user_signed_in? %>
  <%= link_to "Réserver", new_reservation_path, class: "btn btn-primary" %>
<% else %>
  <%= link_to "Réserver", "#", class: "btn btn-primary", onclick: "showLoginAlert()" %>
<% end %>

<% @reservations.each do |reservation| %>
  <div class="card-product">
    <img src="<%= reservation.gear.image_url %>" alt="Image de l'équipement">
    <p>Coût de la location : <%= reservation.cout %> €</p>
    <p>Date de début : <%= reservation.date_debut %></p>
    <p>Date de fin : <%= reservation.date_fin %></p>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
 <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
  <header>
        <nav>
          <ul class="navbar-nav me-auto d-flex flex-row align-items-center justify-content-between w-100">
            <li> <%= link_to root_path do %>
                    <h1 id="logo-title" >GearSwap</h1>
                  <% end %>
            </li>
            <li class="nav-item"> <a href="/gears">Équipements</a></li>
                  <% if user_signed_in? %>
                    <li class="nav-item dropdown">
                    <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <%= image_tag "https://cdn-icons-png.flaticon.com/512/1376/1376641.png", class: "avatar", alt: "dropdown menu" %></a>
                      <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <%= link_to "Profile", profile_path, class: "dropdown-item" %>
                        <%= link_to "Se déconnecter", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
                      </div>
                    </li>
                  <% else %>
                    <li class="nav-item">
                      <%= link_to "Se connecter", new_user_session_path, class: "nav-link" %>
                    </li>
                  <% end %>
          </ul>
        </nav>
    </header>